---
# file: roles/mysql/tasks/main.yml
- name: Install mysql server
  sudo: yes
  apt: name=mysql-server state=present

- name: Install mysql client
  sudo: yes
  apt: name=mysql-client state=present

- name: Install the configuration
  sudo: yes
  template: src=etc/mysql/my.cnf.j2 dest=/etc/mysql/my.cnf